name = "Scydventure"
author = "scyfar"
version = "0.0.1_1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad26e93e18cb5ebc331e6193ae34731b84b6e573c00c0db18fee50302e1eb78a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
