name = "Scydventure"
author = "scyfar"
version = "0.0.1-draft_1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6ad117895a022bf25eebd978c3e6e42bb089beaca323c72a8fae7314ee0c79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
