name: build and deploy pages

on:
  # Run only on `main` branch
  push:
    branches: ["main"]

  # Allow manual runs
  workflow_dispatch:

# Set permissions to allow to publish to Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one build for Pages runs and do not cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install mdbook and alert plugin
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install mdbook mdbook-alerts
      - name: setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: build book
        run: mdbook build book
      - name: upload book files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
